"""remove is_admin column

Revision ID: 5ce6e9f61df5
Revises: 425412960764
Create Date: 2022-08-09 17:20:29.294951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5ce6e9f61df5"
down_revision = "425412960764"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_admin")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("is_admin", sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
